# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from open_manipulator_msgs/OpenManipulatorState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class OpenManipulatorState(genpy.Message):
  _md5sum = "35c95327a0dcb52791892bac52df33e8"
  _type = "open_manipulator_msgs/OpenManipulatorState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """########################################
# CONSTANTS
########################################
string IS_MOVING = "IS_MOVING"
string STOPPED = "STOPPED"
string ACTUATOR_ENABLED = "ACTUATOR_ENABLED"
string ACTUATOR_DISABLED = "ACTUATOR_DISABLED"

########################################
# Messages
########################################
string open_manipulator_moving_state
string open_manipulator_actuator_state
"""
  # Pseudo-constants
  IS_MOVING = r'"IS_MOVING"'
  STOPPED = r'"STOPPED"'
  ACTUATOR_ENABLED = r'"ACTUATOR_ENABLED"'
  ACTUATOR_DISABLED = r'"ACTUATOR_DISABLED"'

  __slots__ = ['open_manipulator_moving_state','open_manipulator_actuator_state']
  _slot_types = ['string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       open_manipulator_moving_state,open_manipulator_actuator_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OpenManipulatorState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.open_manipulator_moving_state is None:
        self.open_manipulator_moving_state = ''
      if self.open_manipulator_actuator_state is None:
        self.open_manipulator_actuator_state = ''
    else:
      self.open_manipulator_moving_state = ''
      self.open_manipulator_actuator_state = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.open_manipulator_moving_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.open_manipulator_actuator_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.open_manipulator_moving_state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.open_manipulator_moving_state = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.open_manipulator_actuator_state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.open_manipulator_actuator_state = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.open_manipulator_moving_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.open_manipulator_actuator_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.open_manipulator_moving_state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.open_manipulator_moving_state = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.open_manipulator_actuator_state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.open_manipulator_actuator_state = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
