// Generated by gencpp from file open_manipulator_msgs/GetKinematicsPose.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_GETKINEMATICSPOSE_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_GETKINEMATICSPOSE_H

#include <ros/service_traits.h>


#include <open_manipulator_msgs/GetKinematicsPoseRequest.h>
#include <open_manipulator_msgs/GetKinematicsPoseResponse.h>


namespace open_manipulator_msgs
{

struct GetKinematicsPose
{

typedef GetKinematicsPoseRequest Request;
typedef GetKinematicsPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetKinematicsPose
} // namespace open_manipulator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_msgs::GetKinematicsPose > {
  static const char* value()
  {
    return "2fe60b9f4a4b683c14e60a854bb9e0e1";
  }

  static const char* value(const ::open_manipulator_msgs::GetKinematicsPose&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_msgs::GetKinematicsPose > {
  static const char* value()
  {
    return "open_manipulator_msgs/GetKinematicsPose";
  }

  static const char* value(const ::open_manipulator_msgs::GetKinematicsPose&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_msgs::GetKinematicsPoseRequest> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::GetKinematicsPose >
template<>
struct MD5Sum< ::open_manipulator_msgs::GetKinematicsPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetKinematicsPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::GetKinematicsPoseRequest> should match
// service_traits::DataType< ::open_manipulator_msgs::GetKinematicsPose >
template<>
struct DataType< ::open_manipulator_msgs::GetKinematicsPoseRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetKinematicsPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_msgs::GetKinematicsPoseResponse> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::GetKinematicsPose >
template<>
struct MD5Sum< ::open_manipulator_msgs::GetKinematicsPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetKinematicsPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::GetKinematicsPoseResponse> should match
// service_traits::DataType< ::open_manipulator_msgs::GetKinematicsPose >
template<>
struct DataType< ::open_manipulator_msgs::GetKinematicsPoseResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetKinematicsPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_GETKINEMATICSPOSE_H
