// Generated by gencpp from file open_manipulator_msgs/SetActuatorState.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_SETACTUATORSTATE_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_SETACTUATORSTATE_H

#include <ros/service_traits.h>


#include <open_manipulator_msgs/SetActuatorStateRequest.h>
#include <open_manipulator_msgs/SetActuatorStateResponse.h>


namespace open_manipulator_msgs
{

struct SetActuatorState
{

typedef SetActuatorStateRequest Request;
typedef SetActuatorStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetActuatorState
} // namespace open_manipulator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_msgs::SetActuatorState > {
  static const char* value()
  {
    return "ad1d166d833769046644494dd3607bd2";
  }

  static const char* value(const ::open_manipulator_msgs::SetActuatorState&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_msgs::SetActuatorState > {
  static const char* value()
  {
    return "open_manipulator_msgs/SetActuatorState";
  }

  static const char* value(const ::open_manipulator_msgs::SetActuatorState&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_msgs::SetActuatorStateRequest> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::SetActuatorState >
template<>
struct MD5Sum< ::open_manipulator_msgs::SetActuatorStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::SetActuatorState >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetActuatorStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::SetActuatorStateRequest> should match
// service_traits::DataType< ::open_manipulator_msgs::SetActuatorState >
template<>
struct DataType< ::open_manipulator_msgs::SetActuatorStateRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::SetActuatorState >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetActuatorStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_msgs::SetActuatorStateResponse> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::SetActuatorState >
template<>
struct MD5Sum< ::open_manipulator_msgs::SetActuatorStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::SetActuatorState >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetActuatorStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::SetActuatorStateResponse> should match
// service_traits::DataType< ::open_manipulator_msgs::SetActuatorState >
template<>
struct DataType< ::open_manipulator_msgs::SetActuatorStateResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::SetActuatorState >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetActuatorStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_SETACTUATORSTATE_H
