// Generated by gencpp from file open_manipulator_msgs/SetJointPosition.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_SETJOINTPOSITION_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_SETJOINTPOSITION_H

#include <ros/service_traits.h>


#include <open_manipulator_msgs/SetJointPositionRequest.h>
#include <open_manipulator_msgs/SetJointPositionResponse.h>


namespace open_manipulator_msgs
{

struct SetJointPosition
{

typedef SetJointPositionRequest Request;
typedef SetJointPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointPosition
} // namespace open_manipulator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_msgs::SetJointPosition > {
  static const char* value()
  {
    return "a524a493b17854dbb5e253d2e23c3001";
  }

  static const char* value(const ::open_manipulator_msgs::SetJointPosition&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_msgs::SetJointPosition > {
  static const char* value()
  {
    return "open_manipulator_msgs/SetJointPosition";
  }

  static const char* value(const ::open_manipulator_msgs::SetJointPosition&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_msgs::SetJointPositionRequest> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::SetJointPosition >
template<>
struct MD5Sum< ::open_manipulator_msgs::SetJointPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetJointPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::SetJointPositionRequest> should match
// service_traits::DataType< ::open_manipulator_msgs::SetJointPosition >
template<>
struct DataType< ::open_manipulator_msgs::SetJointPositionRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetJointPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_msgs::SetJointPositionResponse> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::SetJointPosition >
template<>
struct MD5Sum< ::open_manipulator_msgs::SetJointPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetJointPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::SetJointPositionResponse> should match
// service_traits::DataType< ::open_manipulator_msgs::SetJointPosition >
template<>
struct DataType< ::open_manipulator_msgs::SetJointPositionResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetJointPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_SETJOINTPOSITION_H
