// Generated by gencpp from file open_manipulator_msgs/SetKinematicsPose.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_SETKINEMATICSPOSE_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_SETKINEMATICSPOSE_H

#include <ros/service_traits.h>


#include <open_manipulator_msgs/SetKinematicsPoseRequest.h>
#include <open_manipulator_msgs/SetKinematicsPoseResponse.h>


namespace open_manipulator_msgs
{

struct SetKinematicsPose
{

typedef SetKinematicsPoseRequest Request;
typedef SetKinematicsPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetKinematicsPose
} // namespace open_manipulator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_msgs::SetKinematicsPose > {
  static const char* value()
  {
    return "cce8ad8b6eb29e4b0e3449a09848786e";
  }

  static const char* value(const ::open_manipulator_msgs::SetKinematicsPose&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_msgs::SetKinematicsPose > {
  static const char* value()
  {
    return "open_manipulator_msgs/SetKinematicsPose";
  }

  static const char* value(const ::open_manipulator_msgs::SetKinematicsPose&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_msgs::SetKinematicsPoseRequest> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::SetKinematicsPose >
template<>
struct MD5Sum< ::open_manipulator_msgs::SetKinematicsPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::SetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetKinematicsPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::SetKinematicsPoseRequest> should match
// service_traits::DataType< ::open_manipulator_msgs::SetKinematicsPose >
template<>
struct DataType< ::open_manipulator_msgs::SetKinematicsPoseRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::SetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetKinematicsPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_msgs::SetKinematicsPoseResponse> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::SetKinematicsPose >
template<>
struct MD5Sum< ::open_manipulator_msgs::SetKinematicsPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::SetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetKinematicsPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::SetKinematicsPoseResponse> should match
// service_traits::DataType< ::open_manipulator_msgs::SetKinematicsPose >
template<>
struct DataType< ::open_manipulator_msgs::SetKinematicsPoseResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::SetKinematicsPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::SetKinematicsPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_SETKINEMATICSPOSE_H
